
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.*;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException; 
import javax.swing.JOptionPane;

//Improvements maybe: Try putting the operations and etc into an array and make it check against the array

/**
 *
 * @author Jacky
 */
public class Calculator extends javax.swing.JFrame {
    String[] Operations = {"/" , "*" , "-" , "+" , "."};
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        setIcon();
        
        //Display.setHorizontalAlignment(Display.RIGHT); Makes text go from right to left
    }
    
    
    public void ClickSound(){
        //https://www.youtube.com/watch?v=syGFTx7iQio&list=LL5Wq08iyF2_OSNgKec_qpAQ
        InputStream in;
        try{
            in = new FileInputStream(new File ("E:\\Netbeans\\Calculator\\Click.wav"));
            AudioStream audio = new AudioStream(in);
            AudioPlayer.player.start(audio);
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
    public void History(String Equation, String Result) throws IOException{
        File file = new File("History.txt");
        FileWriter fw = new FileWriter(file, true);
        PrintWriter pw = new PrintWriter(fw);
        if (Result.equals("")){
            
            Result = "Error";
        }
      
        pw.println(Equation + " = " + Result);
        pw.close();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyPanel = new javax.swing.JPanel();
        ThreeBtn = new javax.swing.JButton();
        SevenBtn = new javax.swing.JButton();
        MinusBtn = new javax.swing.JButton();
        EightBtn = new javax.swing.JButton();
        ZeroBtn = new javax.swing.JButton();
        NineBtn = new javax.swing.JButton();
        DotBtn = new javax.swing.JButton();
        DivideBtn = new javax.swing.JButton();
        EqualsBtn = new javax.swing.JButton();
        FourBtn = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        FiveBtn = new javax.swing.JButton();
        SixBtn = new javax.swing.JButton();
        MultiplyBtn = new javax.swing.JButton();
        OpenBracketBtn = new javax.swing.JButton();
        CloseBracketBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        OneBtn = new javax.swing.JButton();
        ClearAllBtn = new javax.swing.JButton();
        TwoBtn = new javax.swing.JButton();
        HistoryBtn = new javax.swing.JButton();
        Display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jacky's Calculator");
        setIconImages(null);
        setResizable(false);

        MyPanel.setEnabled(false);

        ThreeBtn.setText("3");
        ThreeBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeBtnActionPerformed(evt);
            }
        });

        SevenBtn.setText("7");
        SevenBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenBtnActionPerformed(evt);
            }
        });

        MinusBtn.setText("-");
        MinusBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MinusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusBtnActionPerformed(evt);
            }
        });

        EightBtn.setText("8");
        EightBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        EightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightBtnActionPerformed(evt);
            }
        });

        ZeroBtn.setText("0");
        ZeroBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ZeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroBtnActionPerformed(evt);
            }
        });

        NineBtn.setText("9");
        NineBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        NineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineBtnActionPerformed(evt);
            }
        });

        DotBtn.setText(".");
        DotBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DotBtnActionPerformed(evt);
            }
        });

        DivideBtn.setText("/");
        DivideBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DivideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideBtnActionPerformed(evt);
            }
        });

        EqualsBtn.setText("=");
        EqualsBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        EqualsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqualsBtnActionPerformed(evt);
            }
        });

        FourBtn.setText("4");
        FourBtn.setToolTipText("");
        FourBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        FourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourBtnActionPerformed(evt);
            }
        });

        AddBtn.setText("+");
        AddBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        FiveBtn.setText("5");
        FiveBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        FiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveBtnActionPerformed(evt);
            }
        });

        SixBtn.setText("6");
        SixBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixBtnActionPerformed(evt);
            }
        });

        MultiplyBtn.setText("*");
        MultiplyBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        MultiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplyBtnActionPerformed(evt);
            }
        });

        OpenBracketBtn.setText("(");
        OpenBracketBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        OpenBracketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBracketBtnActionPerformed(evt);
            }
        });

        CloseBracketBtn.setText(")");
        CloseBracketBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CloseBracketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBracketBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        OneBtn.setText("1");
        OneBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        OneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneBtnActionPerformed(evt);
            }
        });

        ClearAllBtn.setText("Clear All");
        ClearAllBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ClearAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearAllBtnActionPerformed(evt);
            }
        });

        TwoBtn.setText("2");
        TwoBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoBtnActionPerformed(evt);
            }
        });

        HistoryBtn.setText("History");
        HistoryBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        HistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryBtnActionPerformed(evt);
            }
        });

        Display.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setText("0");
        Display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Display.setFocusable(false);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MyPanelLayout = new javax.swing.GroupLayout(MyPanel);
        MyPanel.setLayout(MyPanelLayout);
        MyPanelLayout.setHorizontalGroup(
            MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Display)
                    .addGroup(MyPanelLayout.createSequentialGroup()
                        .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MyPanelLayout.createSequentialGroup()
                                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MyPanelLayout.createSequentialGroup()
                                        .addComponent(OneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MyPanelLayout.createSequentialGroup()
                                        .addComponent(ZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MyPanelLayout.createSequentialGroup()
                                        .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(SevenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(OpenBracketBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(FourBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(MyPanelLayout.createSequentialGroup()
                                                .addComponent(CloseBracketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(MyPanelLayout.createSequentialGroup()
                                                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(FiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(SixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(NineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(ThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EqualsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DivideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ClearAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MultiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(HistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MyPanelLayout.setVerticalGroup(
            MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenBracketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CloseBracketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DivideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MultiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TwoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ThreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MinusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DotBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("1"); 
        }
        else{
            Display.setText(Display.getText() + "1");
        }
        
    }//GEN-LAST:event_OneBtnActionPerformed

    private void OpenBracketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBracketBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("("); 
        }
        else{
            Display.setText(Display.getText() + "(");
        }
    }//GEN-LAST:event_OpenBracketBtnActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        
    }//GEN-LAST:event_DisplayActionPerformed

    private void ClearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearAllBtnActionPerformed
        ClickSound();
        Font f = new Font("Tahoma",Font.PLAIN,36);
        Display.setFont(f);
        Display.setText("0");
        OpenBracketBtn.setEnabled(true);
        CloseBracketBtn.setEnabled(true);
        DivideBtn.setEnabled(true);
        MultiplyBtn.setEnabled(true);
        AddBtn.setEnabled(true);
        MinusBtn.setEnabled(true);
        OneBtn.setEnabled(true);
        TwoBtn.setEnabled(true);
        ThreeBtn.setEnabled(true);
        FourBtn.setEnabled(true);
        FiveBtn.setEnabled(true);
        SixBtn.setEnabled(true);
        SevenBtn.setEnabled(true);
        EightBtn.setEnabled(true);
        NineBtn.setEnabled(true);
        ZeroBtn.setEnabled(true);
        DotBtn.setEnabled(true);
        EqualsBtn.setEnabled(true);
        DeleteBtn.setEnabled(true);    
    }//GEN-LAST:event_ClearAllBtnActionPerformed

    private void TwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("2"); 
        }
        else{
            Display.setText(Display.getText() + "2");
        }
    }//GEN-LAST:event_TwoBtnActionPerformed

    private void ThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("3"); 
        }
        else{
            Display.setText(Display.getText() + "3");
        }
    }//GEN-LAST:event_ThreeBtnActionPerformed

    private void FourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("4"); 
        }
        else{
            Display.setText(Display.getText() + "4");
        }
    }//GEN-LAST:event_FourBtnActionPerformed

    private void FiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("5"); 
        }
        else{
            Display.setText(Display.getText() + "5");
        }
    }//GEN-LAST:event_FiveBtnActionPerformed

    private void SixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("6"); 
        }
        else{
            Display.setText(Display.getText() + "6");
        }
    }//GEN-LAST:event_SixBtnActionPerformed

    private void SevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("7"); 
        }
        else{
            Display.setText(Display.getText() + "7");
        }
    }//GEN-LAST:event_SevenBtnActionPerformed

    private void EightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("8"); 
        }
        else{
            Display.setText(Display.getText() + "8");
        }
    }//GEN-LAST:event_EightBtnActionPerformed

    private void NineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("9"); 
        }
        else{
            Display.setText(Display.getText() + "9");
        }
    }//GEN-LAST:event_NineBtnActionPerformed

    private void ZeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText("0"); 
        }
        else{
            Display.setText(Display.getText() + "0");
        }
    }//GEN-LAST:event_ZeroBtnActionPerformed

    private void CloseBracketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBracketBtnActionPerformed
        ClickSound();
        if (Display.getText().equals("0")){
           Display.setText(")"); 
        }
        else{
            Display.setText(Display.getText() + ")");
        }
    }//GEN-LAST:event_CloseBracketBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        ClickSound();
        if (!Display.getText().equals("0")){
            //Takes off Last Character of string
          Display.setText(Display.getText().substring(0, Display.getText().length() - 1));
          //This checks so that if we get to the last digit and we delete it, it will turn the display into a 0
          if (Display.getText().equals("")){
              Display.setText("0");
          }
        }
        
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void DotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DotBtnActionPerformed

        ClickSound();
        //Getting the character in the last position
        char LastCharacter = Display.getText().charAt(Display.getText().length() - 1);
        //Converting the last character into a string
        String LastCharacterString = Character.toString(LastCharacter);
        
        //If the last character of the string is not a ".", then we will allow a "." to be displayed
        if (!LastCharacterString.equals(".")){
            //Add dot onto new display
            Display.setText(Display.getText() + ".");
        }
    }//GEN-LAST:event_DotBtnActionPerformed

    private void DivideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideBtnActionPerformed
        ClickSound();
        boolean CanUse = false;
        //Getting the character in the last position
        char LastCharacter = Display.getText().charAt(Display.getText().length() - 1);
        //Converting the last character into a string
        String LastCharacterString = Character.toString(LastCharacter);   
 
        
        for (int i = 0; i < Operations.length; i++){
            if (LastCharacterString.equals(Operations[i])){
                       CanUse = false;
                       break;
            }
            else{
                CanUse = true;
            }
        }
        if (CanUse){
            Display.setText(Display.getText() + "/");
        }

    }//GEN-LAST:event_DivideBtnActionPerformed

    private void MultiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyBtnActionPerformed
        ClickSound();
        boolean CanUse = false;
        //Getting the character in the last position
        char LastCharacter = Display.getText().charAt(Display.getText().length() - 1);
        //Converting the last character into a string
        String LastCharacterString = Character.toString(LastCharacter);   
 
        
        for (int i = 0; i < Operations.length; i++){
            if (LastCharacterString.equals(Operations[i])){
                       CanUse = false;
                       break;
            }
            else{
                CanUse = true;
            }
        }
        if (CanUse){
            Display.setText(Display.getText() + "*");
        }
    }//GEN-LAST:event_MultiplyBtnActionPerformed

    private void MinusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusBtnActionPerformed
        ClickSound();
        boolean CanUse = false;
        //Getting the character in the last position
        char LastCharacter = Display.getText().charAt(Display.getText().length() - 1);
        //Converting the last character into a string
        String LastCharacterString = Character.toString(LastCharacter);   
        
        if (Display.getText().equals("0")){
            Display.setText("-");
        }
        else{
        for (int i = 0; i < Operations.length; i++){
            if (LastCharacterString.equals(Operations[i])){
                       CanUse = false;
                       break;
            }
            else{
                CanUse = true;
            }
        }
        if (CanUse){
            Display.setText(Display.getText() + "-");
        }
        }       
    }//GEN-LAST:event_MinusBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        ClickSound();
        boolean CanUse = false;
        //Getting the character in the last position
        char LastCharacter = Display.getText().charAt(Display.getText().length() - 1);
        //Converting the last character into a string
        String LastCharacterString = Character.toString(LastCharacter);   
 
        
        for (int i = 0; i < Operations.length; i++){
            if (LastCharacterString.equals(Operations[i])){
                       CanUse = false;
                       break;
            }
            else{
                CanUse = true;
            }
        }
        if (CanUse){
            Display.setText(Display.getText() + "+");
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void EqualsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqualsBtnActionPerformed
        ClickSound();
        //https://stackoverflow.com/questions/2605032/is-there-an-eval-function-in-java        
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("js");
        String Equation = Display.getText();
        Object result;
        String Result = "";
        boolean Correct = false;
        
        
        //we start at int i = 1 because we cant look at position 0-1 and even if the ( is in the first position, it wont need a * sign on it.
        for (int i = 1; i < Display.getText().length(); i++){
            //variable to get the individual character
            char Term = Equation.charAt(i);
            //variable to get the individual character behind the first one
            char Term1 = Equation.charAt(i-1);   
            if (Character.toString(Term).matches("\\(") && ((!Character.toString(Term1).matches("\\+")) && (!Character.toString(Term1).matches("-")) && (!Character.toString(Term1).matches("/")) && (!Character.toString(Term1).matches("\\*")))){
                Equation = Equation.substring(0, i) + "*" + Equation.substring(i, Equation.length());
                break;
            }
        } 
        
        try {
            result = engine.eval(Equation);
            Correct = true;
            Result = result.toString();
        } 
        catch (ScriptException ex) { 
            Font f = new Font("Tahoma",Font.PLAIN,20);
            Display.setFont(f);
            Display.setText("Error. Press 'Clear All' to Restart Calculator.");
            OpenBracketBtn.setEnabled(false);
            CloseBracketBtn.setEnabled(false);
            DivideBtn.setEnabled(false);
            MultiplyBtn.setEnabled(false);
            AddBtn.setEnabled(false);
            MinusBtn.setEnabled(false);
            OneBtn.setEnabled(false);
            TwoBtn.setEnabled(false);
            ThreeBtn.setEnabled(false);
            FourBtn.setEnabled(false);
            FiveBtn.setEnabled(false);
            SixBtn.setEnabled(false);
            SevenBtn.setEnabled(false);
            EightBtn.setEnabled(false);
            NineBtn.setEnabled(false);
            ZeroBtn.setEnabled(false);
            DotBtn.setEnabled(false);
            EqualsBtn.setEnabled(false);
            DeleteBtn.setEnabled(false);      
        }
        
        
        try {
            History(Equation, Result);
        } catch (IOException ex) {
            Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if (Correct == true){
            Display.setText(Result);
        }
        
        
               
    }//GEN-LAST:event_EqualsBtnActionPerformed

    private void HistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryBtnActionPerformed
        ClickSound();
        
        
        try {           
            History OpenHistory = new History();
            OpenHistory.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Calculator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_HistoryBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    
    
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("CalculatorLogo.JPG")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton ClearAllBtn;
    private javax.swing.JButton CloseBracketBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField Display;
    private javax.swing.JButton DivideBtn;
    private javax.swing.JButton DotBtn;
    private javax.swing.JButton EightBtn;
    private javax.swing.JButton EqualsBtn;
    private javax.swing.JButton FiveBtn;
    private javax.swing.JButton FourBtn;
    private javax.swing.JButton HistoryBtn;
    private javax.swing.JButton MinusBtn;
    private javax.swing.JButton MultiplyBtn;
    private javax.swing.JPanel MyPanel;
    private javax.swing.JButton NineBtn;
    private javax.swing.JButton OneBtn;
    private javax.swing.JButton OpenBracketBtn;
    private javax.swing.JButton SevenBtn;
    private javax.swing.JButton SixBtn;
    private javax.swing.JButton ThreeBtn;
    private javax.swing.JButton TwoBtn;
    private javax.swing.JButton ZeroBtn;
    // End of variables declaration//GEN-END:variables
}
